#!/bin/bash

BIN=/home/svampis/Daidai/bin

if [ $# -lt 1 ]
then
	echo "daidai.sh: give a file"
	exit 4
fi
filename=$1

if ! [ -f $filename.dai ]
then
	echo "q" | $BIN/daidai -f=$filename.dai -c=$(wc -l $filename | cut -f1 -d ' ') 4 3 2 1 > /dev/null
fi

coproc DAIDAI { stdbuf -oL $BIN/daidai -f=$filename.dai ; }

while :
do
	read -r flashcard_id <&"${DAIDAI[0]}"
	head -n $(expr $flashcard_id + 1) < $filename | tail -n 1 | cut -f2 | tr -d '\n'
	printf ": "
	read -r input
	clear
	if [ "$input" = "q" ]
	then
		echo "q" >&"${DAIDAI[1]}"
		echo "Goodbye"
		break
	elif [ "$input" = $(head -n $(expr $flashcard_id + 1) < $filename | tail -n 1 | cut -f1) ]
	then
		echo "y" >&"${DAIDAI[1]}"
		echo "Correct"
	else
		echo "n" >&"${DAIDAI[1]}"
		strokeorder $(head -n $(expr $flashcard_id + 1) < $filename | tail -n 1 | cut -f3)
		head -n $(expr $flashcard_id + 1) < $filename | tail -n 1
	fi
done

